### ISSUE TITLE
Just a couple questions :)

### ISSUE THREAD

**Issue by stephenfuga** [hramos/helpscout#18]
Does the gem in the future plan to interact with the other API like the social network fields? Do you think one day I would be able to utilise your gem to trigger sending of certain emails in ruby? 

Thanks in advance for all your time. I am loving this gem so far and it works really well and you've documented everything great!

Cheers!

**Comment by hramos** [comment]
I don't have any concrete plans for the gem at the moment. For some background, this is a gem I wrote about five years ago for a specific use case for which it served me well. I'm not actively using HelpScout at the moment, so I wouldn't expect big changes to come to the gem.
